### ISSUE TITLE
Proper handling of components with Position::Absolute

### ISSUE THREAD

**Issue by jrmoulton** [lapce/floem#47]
When items are given position absolute the items that should be underneath them just render on the "same layer". They just overlap each other. Background's don't cover up other elements and the "top" element stops receiving events.

https://github.com/lapce/floem/assets/13090441/c23d5000-937d-4929-a96e-62d6ad1961ba

**Comment by dzhou121** [comment]
We'll need to introduce z-index to fix this one.

**Comment by dzhou121** [comment]
Can you try 3db00234535516b62eb6da0053bf3602bdcac22a which should fix the rendering if you set a higher z-index on the dropdown.

**Comment by jrmoulton** [comment]
It does render correctly but it still doesn't receive events when it overflows the size of the parent

**Comment by dzhou121** [comment]
This f921212204b0c85c5571e3e95d0d057c0faba5b5 should fix the event handling.

**Comment by jrmoulton** [comment]
Works perfectly! I'll go ahead and close the issue
